import { Inter } from "next/font/google";
// import "./globals.css"; -> Tire esta linha
import 'bootstrap/dist/css/bootstrap.min.css'; //Pegue isso do site

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
